### ISSUE TITLE
Comment model need "onDelete: Cascade"

### ISSUE THREAD

**Issue by snettah** [redwoodjs/learn.redwoodjs.com#175]
https://learn.redwoodjs.com/docs/tutorial2/adding-comments-to-the-schema/#adding-the-comment-model

The relation with Post need `onDelete: Cascade` to work properly

```
model Comment {
  id        Int      @id @default(autoincrement())
  name      String
  body      String
  post      Post     @relation(fields: [postId], references: [id], onDelete: Cascade)
  postId    Int
  createdAt DateTime @default(now())
}
```

**Comment by clairefro** [comment]
@cannikin

**Comment by cannikin** [comment]
Hmm, let me think about this one. I'm not too thrilled with the idea of getting into descriptions of referential integrity in this tutorial, it's meant to be a pretty high-level overview of things, focusing on building and integrating components at this point. I assume that trying to delete a post is failing? I don't think we demonstrate doing that at this point (or later) in the tutorial, but I if someone goes off-script...

**Comment by snettah** [comment]
If we follow the tutorial we'll have this error https://github.com/redwoodjs/redwood/issues/3680#issue-1041413694

**Comment by cannikin** [comment]
You get that when running the test suite? We've released a patch that should have fixed that issue. Or are you seeing this error somewhere else?

**Comment by snettah** [comment]
> You get that when running the test suite? We've released a patch that should have fixed that issue. Or are you seeing this error somewhere else?

I don't know when have you release the patch, I've got this error yesterday when I run the tests suit

**Comment by cannikin** [comment]
It’s been several versions ago…what does `yarn require info` output?

We haven’t had anyone else reporting this problem as far as I know so this is very unusual!

**Comment by davidlcorbitt** [comment]
I'm seeing the same problem.  The error happens when running the default 'returns all comments' test in `comments.test.js`.

Here's the exact text of the error:
```
Invalid `prisma.executeRaw()` invocation:


      Raw query failed. Code: `23503`. Message: `update or delete on table "Post" violates foreign key constraint "Comment_postId_fkey" on table "Comment"
```

Here's a screenshot of the test initially failing:
![Screen Shot 2022-01-18 at 3 27 28 PM](https://user-images.githubusercontent.com/41524992/150030010-88bbd1ec-b6f4-4d5d-867c-a9ffdcac2f0d.png)


I have a theory as to why this is happening.  When the test attempts to clean up the test database after itself and delete all `Comment`s and `Post`s that it created, it first tries to delete the `Post`s.  However, a `Comment` (as we've defined it in our `schema.prisma` file) needs to have a `Post` associated with it.  Therefore, when we try to delete a `Post` that has `Comment`s associated with it, the `prisma.executeRaw()` invocation errors and we are informed that we cannot delete any `Post` whose ID with is the foreign key of any `Comment`.

When I run this test again without changing anything (cmd+s in any file will trigger a rerun) I am presented by a different failing error message:
![Screen Shot 2022-01-18 at 3 28 14 PM](https://user-images.githubusercontent.com/41524992/150030699-865975e7-db50-46ad-92ac-d59f426d3286.png)

Here we can see that four comments, not two, are present in the database.  I printed out the comments data our test is getting and included them below:
```
    [
      {
        id: 1,
        name: 'Jane Doe',
        body: 'I like trees',
        postId: 1,
        createdAt: 2022-01-18T22:27:05.690Z
      },
      {
        id: 2,
        name: 'John Doe',
        body: 'Hug a tree today',
        postId: 2,
        createdAt: 2022-01-18T22:27:05.700Z
      },
      {
        id: 3,
        name: 'Jane Doe',
        body: 'I like trees',
        postId: 3,
        createdAt: 2022-01-18T22:27:35.384Z
      },
      {
        id: 4,
        name: 'John Doe',
        body: 'Hug a tree today',
        postId: 4,
        createdAt: 2022-01-18T22:27:35.390Z
      }
    ]
```
As we can see, the previous comments were never deleted.  After making the change to include `onDelete: Cascade` as @snettah suggests and restarting the tests, they passed without error.

**Comment by davidlcorbitt** [comment]
Here's my `yarn rw info` output:

```
  System:
    OS: macOS 11.6.2
    Shell: 5.0.0 - /usr/local/bin/bash
  Binaries:
    Node: 14.17.4 - /var/folders/8h/fv678_ls5fq37zsct22jk91h0000gn/T/yarn--1642547796280-0.6210085078811798/node
    Yarn: 1.22.17 - /var/folders/8h/fv678_ls5fq37zsct22jk91h0000gn/T/yarn--1642547796280-0.6210085078811798/yarn
  Databases:
    SQLite: 3.32.2 - /Users/admin/Library/Android/sdk/platform-tools/sqlite3
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 15.2
  npmPackages:
    @redwoodjs/core: ^0.38.0 => 0.38.0
```

The strange thing is that I'm actually not using SQLite as my database anymore, I'm using postgresql.  I'm not sure if I missed a step in updating my database info for RedwoodJS (it's working with postgresql locally and in production), but that could be the reason that only a few people see this error.  It might not happen for people using SQLite.

**Comment by davidlcorbitt** [comment]
@snettah have you tried upgrading to the latest version of RedwoodJS?  That solved the problem for me.

**Comment by davidlcorbitt** [comment]
@cannikin we should probably update the example tutorial referenced in the [Tutorial II Prerequisites](https://learn.redwoodjs.com/docs/tutorial2/prerequisites) to be the latest version of RedwoodJS.

Excerpt from current example tutorial [package.json ](https://github.com/redwoodjs/redwood-tutorial/blob/main/package.json) file: 
```
  "devDependencies": {
    "@redwoodjs/core": "^0.38.0"
  },
```

This means that if the reader doesn't run `yarn redwood upgrade`, by default they'll be using a version of RedwoodJS in which this test will error.

**Comment by cannikin** [comment]
Yep, tutorial updates for v1.0 are in progress as we speak! https://github.com/redwoodjs/learn.redwoodjs.com/pull/173

**Comment by davidlcorbitt** [comment]
Actually, I don't think this is an issue with the documentation in Tutorial I.  This problem comes up in Tutorial II when the reader starts with this cloned repository: https://github.com/redwoodjs/redwood-tutorial.  Am I missing something?

**Comment by cannikin** [comment]
Ahhh that could be it—we haven't updated that repo in a while and it may be missing the fix for the test deletes! I'll create an issue to update.

**Comment by cannikin** [comment]
Thanks to this PR https://github.com/redwoodjs/redwood-tutorial/issues/17 this should be closed! Feel free to re-open if you've tried starting from this point (or updated Redwood to the latest version in your tutorial app). Thanks for the fix @davidlcorbitt!
